

# Language specifications

language: python
python:
    - "2.6"
    - "2.7"

# Dependencies

install:
    - pip install --use-mirrors -r optional-requirements.txt


# Test script

script: python test/run_tests.py


